# Generated by Django 5.0.1 on 2024-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
        ('posts', '0008_alter_topic_options_topic_order_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='api.profile'),
        ),
    ]
