# Generated by Django 5.0.1 on 2024-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSections',
            fields=[
                ('lesson_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_section_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionsClassrooms',
            fields=[
                ('lesson_sections_classrooms_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_sections_classrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionsStudents',
            fields=[
                ('lesson_sections_students_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lesson_sections_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionsTeachers',
            fields=[
                ('lesson_sections_teachers_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lesson_sections_teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
    ]
