# Generated by Django 5.0.1 on 2024-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_section_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_section_classroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lesson_section_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSectionTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lesson_section_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Classrooms',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='LessonSections',
        ),
        migrations.DeleteModel(
            name='LessonSectionsClassrooms',
        ),
        migrations.DeleteModel(
            name='LessonSectionsStudents',
        ),
        migrations.DeleteModel(
            name='LessonSectionsTeachers',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
