# Generated by Django 5.1.1 on 2024-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lessonsection_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
