# Generated by Django 5.1.1 on 2025-02-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_timeemptyclassroom_time_empty__time_14541b_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mail',
            new_name='mail_etu',
        ),
    ]
