# Generated by Django 5.1.1 on 2024-10-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lessonsection_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonsectionclassroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonsectionstudent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonsectionteacher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
