# Generated by Django 5.1.1 on 2025-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_mail_student_mail_etu'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
