# Generated by Django 5.1.1 on 2025-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_mail_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
    ]
