# Generated by Django 5.1.1 on 2025-02-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='favorites',
        ),
    ]
